
services:
  app:
    volumes:
      - ./templates:/var/www/html/templates:ro
      - ./src:/var/www/html/src:ro
      - ./config:/var/www/html/config:ro
      - ./translations:/var/www/html/translations:ro
      - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
    environment:
      GOOGLE_REDIRECT_URI: http://localhost:8090/connect/google/callback

  nginx:
    ports:
      - "8090:80"

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###
