<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * LearnAdapt Mind — mind_reports table
 *
 * Stores the weekly cognitive learning reports generated by LearnerContextBuilder + Groq.
 */
final class Version20260502000001 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create mind_reports table for LearnAdapt Mind weekly cognitive reports';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('
            CREATE TABLE mind_reports (
                id          BIGINT AUTO_INCREMENT NOT NULL,
                user_id     BIGINT NOT NULL,
                week_start  DATE NOT NULL,
                week_end    DATE NOT NULL,
                metrics     JSON NOT NULL COMMENT "All computed numeric metrics (JSON)",
                ai_narrative LONGTEXT DEFAULT NULL COMMENT "Groq-generated or offline narrative text",
                health_score TINYINT UNSIGNED NOT NULL DEFAULT 50 COMMENT "0-100 composite health score",
                groq_used   TINYINT(1) NOT NULL DEFAULT 0 COMMENT "1 = Groq API was used, 0 = offline fallback",
                created_at  DATETIME NOT NULL,
                UNIQUE INDEX uq_user_week (user_id, week_start),
                INDEX idx_mr_user (user_id),
                PRIMARY KEY (id)
            ) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
        ');

        $this->addSql('
            ALTER TABLE mind_reports
            ADD CONSTRAINT fk_mr_user
                FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
        ');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE mind_reports DROP FOREIGN KEY fk_mr_user');
        $this->addSql('DROP TABLE mind_reports');
    }
}
